//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fmb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fmb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///	margin: 1em;
        ///	padding: 1em;
        ///	font-family: Verdana;
        ///	font-size: 9pt;
        ///	line-height: 1.5;
        ///}
        /// 
        ///h1 a {
        ///	font-size: 12pt;
        ///	color: black;
        ///	background-color: #99d9ea;
        ///	display: inline-box;
        ///	border: 1px solid black;
        ///	padding: .5em;
        ///}
        ///
        ///h2 {
        ///	font-size: 10pt;
        ///	margin: 0;
        ///	padding-top: 1em;
        ///}
        /// 
        ///a, a:active { 
        ///	text-decoration: none;
        ///	color: blue;
        ///}
        ///
        ///a:hover {
        ///	text-decoration: underline;
        ///}
        ///
        ///fieldset {
        ///	border: 0;
        ///	background-color: #efefef;
        ///}
        ///
        ///button, input {
        ///	font-family: Verdana;
        ///	font-size: 9pt }
        ///
        ///div [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stylesheet {
            get {
                return ResourceManager.GetString("stylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        ///
        ///&lt;ul&gt;  
        ///	&lt;li&gt;&lt;a href = &quot;?servlet=ServletForm&amp;form=HtmlFormShowWebpage&quot;&gt;Show webpage&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string TplActions {
            get {
                return ResourceManager.GetString("TplActions", resourceCulture);
            }
        }

        internal static string TplLibrary
        {
            get
            {
                return ResourceManager.GetString("TplLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;div id = &quot;footer&quot;&gt;
        /// &lt;strong&gt;Version: &lt;/strong&gt; {$PROGRAM_VERSION} &lt;strong&gt;Project Website: &lt;/strong&gt;&lt;a href = &quot;http://sourceforge.net/projects/fmb/&quot;&gt;http://sourceforge.net/projects/fmb/&lt;/a&gt; &lt;strong&gt;Copyright:&lt;/strong&gt; &amp;copy; fmb development team
        /// &lt;/div&gt;
        /// &lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string TplFooter {
            get {
                return ResourceManager.GetString("TplFooter", resourceCulture);
            }
        }
        
        internal static string TplYouTube
        {
            get { 
                return ResourceManager.GetString("TplYouTubeVideo", resourceCulture);
            }
        }

        internal static string TplPresentationHelp
        {
            get
            {
                return ResourceManager.GetString("TplPresentationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;fmb&lt;/title&gt;
        ///    &lt;link rel = &quot;stylesheet&quot; type = &quot;text/css&quot; href = &quot;?servlet=ServletResource&amp;amp;filename=stylesheet&quot; /&gt;
        ///  &lt;/head&gt;  
        ///  &lt;body&gt;
        ///&lt;div id = &quot;header&quot;&gt; 
        ///  &lt;h1&gt;
        ///    &lt;a href = &quot;?servlet=ServletIndex&quot;&gt;fmb&lt;/a&gt;
        ///  &lt;/h1&gt; 
        ///  
        ///  {$QUICK_NAV} 
        ///&lt;/div&gt; 
        ///
        ///    &lt;h2&gt;{$PAGE_TITLE}&lt;/h2&gt;.
        /// </summary>
        internal static string TplHeader {
            get {
                return ResourceManager.GetString("TplHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt; 
        ///  &lt;ul id = &quot;navigation&quot;&gt;
        ///    &lt;li&gt;
        ///      &lt;a href = &quot;?servlet=ServletIndex&quot;&gt;Index&lt;/a&gt;
        ///    &lt;/li&gt;
        ///
        ///    &lt;li&gt;
        ///      &lt;a href = &quot;?servlet=ServletForm&amp;amp;form=HtmlFormSetBounds&quot;&gt;Set Bounds&lt;/a&gt;
        ///    &lt;/li&gt;
        ///
        ///    &lt;li&gt;
        ///      &lt;a href = &quot;?servlet=ServletLibrary&quot;&gt;Library&lt;/a&gt;
        ///    &lt;/li&gt;
        ///
        ///    &lt;li&gt;
        ///      &lt;a href = &quot;?servlet=ServletActions&quot;&gt;Actions&lt;/a&gt;
        ///    &lt;/li&gt;
        ///  &lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string TplNavigation {
            get {
                return ResourceManager.GetString("TplNavigation", resourceCulture);
            }
        }

        internal static string TplError
        {
            get
            {
                return ResourceManager.GetString("TplError", resourceCulture); 
            }
        }

        public static string TplStartup
        {
            get 
            { 
                return ResourceManager.GetString("TplStartup", resourceCulture);
            }
        }
    }
}
